<h1>Background</h1>

<p>Using devices such as Jawbone Up, Nike FuelBand, and Fitbit it is now possible to collect a large amount of data about personal activity relatively inexpensively. These type of devices are part of the quantified self movement – a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it. In this project, your goal will be to use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants. They were asked to perform barbell lifts correctly and incorrectly in 5 different ways. More information is available from the website here: <a href="http://groupware.les.inf.puc-rio.br/har">http://groupware.les.inf.puc-rio.br/har</a> (see the section on the Weight Lifting Exercise Dataset). </p>

<h1>Data </h1>

<p>The training data for this project are available here: </p>

<p><a href="https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv">https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv</a></p>

<p>The test data are available here: </p>

<p><a href="https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv">https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv</a></p>

<p>The data for this project come from this source: <a href="http://groupware.les.inf.puc-rio.br/har">http://groupware.les.inf.puc-rio.br/har</a>. If you use the document you create for this class for any purpose please cite them as they have been very generous in allowing their data to be used for this kind of assignment. </p>

<h1>What you should submit</h1>

<p>The goal of your project is to predict the manner in which they did the exercise. This is the &ldquo;classe&rdquo; variable in the training set. You may use any of the other variables to predict with. You should create a report describing how you built your model, how you used cross validation, what you think the expected out of sample error is, and why you made the choices you did. You will also use your prediction model to predict 20 different test cases. </p>

<ol>
<li>Your submission should consist of a link to a Github repo with your R markdown and compiled HTML file describing your analysis. Please constrain the text of the writeup to &lt; 2000 words and the number of figures to be less than 5. It will make it easier for the graders if you submit a repo with a gh-pages branch so the HTML page can be viewed online (and you always want to make it easy on graders :-).</li>
<li>You should also apply your machine learning algorithm to the 20 test cases available in the test data above. Please submit your predictions in appropriate format to the programming assignment for automated grading. See the programming assignment for additional details. </li>
</ol>

<h1>Reproducibility </h1>

<p>Due to security concerns with the exchange of R code, your code will not be run during the evaluation by your classmates. Please be sure that if they download the repo, they will be able to view the compiled HTML version of your analysis. </p>

<h1>RESULTS</h1>

<p><strong>1.Load required libraries and data files containing the data:</strong></p>

<pre><code class="r"># install.packages(&quot;caret&quot;)
# install.packages(&quot;randomForest&quot;)
# install.packages(&quot;rpart&quot;)
# install.packages(&quot;kernlab&quot;)
# install.packages(&quot;rattle&quot;)
# install.packages(&quot;ipred&quot;)
library(caret)
</code></pre>

<pre><code>## Warning: package &#39;caret&#39; was built under R version 3.1.2
</code></pre>

<pre><code>## Loading required package: lattice
## Loading required package: ggplot2
## Find out what&#39;s changed in ggplot2 with
## news(Version == &quot;1.0.0&quot;, package = &quot;ggplot2&quot;)
## 
## Attaching package: &#39;ggplot2&#39;
## 
## The following object is masked _by_ &#39;.GlobalEnv&#39;:
## 
##     mpg
</code></pre>

<pre><code class="r">library(randomForest)
</code></pre>

<pre><code>## Warning: package &#39;randomForest&#39; was built under R version 3.1.1
</code></pre>

<pre><code>## randomForest 4.6-10
## Type rfNews() to see new features/changes/bug fixes.
</code></pre>

<pre><code class="r">library(rpart)
library(rpart.plot)
</code></pre>

<pre><code>## Warning: package &#39;rpart.plot&#39; was built under R version 3.1.2
</code></pre>

<pre><code class="r">library(rattle)
</code></pre>

<pre><code>## Warning: package &#39;rattle&#39; was built under R version 3.1.1
</code></pre>

<pre><code>## Rattle: A free graphical interface for data mining with R.
## Version 3.3.0 Copyright (c) 2006-2014 Togaware Pty Ltd.
## Type &#39;rattle()&#39; to shake, rattle, and roll your data.
</code></pre>

<pre><code class="r">library(kernlab)
library(ipred)

#Set initial seed for reproducibility
set.seed(54321)

workingDir &lt;- &quot;/Volumes/Data/E-courses/Johns\ Hopkins\ University\ Data\ Science/Practical_Machine_Learning/Project&quot;
#Set the working directory in your computer
setwd(workingDir)

#Check if the files containing the data is already in your working directory. Otherwise, download it, save as a csv file and get the data replacing all missing values as NA
trainingDataURL&lt;-&quot;https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv&quot;
trainFilename&lt;-&quot;trainData.csv&quot;
#Check if the file containing the data is already in your working directory. Otherwise, download it, save as a csv file and get the data replacing all missing values as NA
if (file.exists(trainFilename)) {
        trainingData&lt;-read.csv(trainFilename, na.strings=c(&quot;NA&quot;,&quot;#DIV/0!&quot;, &quot;&quot;))     
} else {
        download.file(trainingDataURL, destfile = trainFilename, method = &quot;curl&quot;)
        trainingData&lt;-read.csv(trainFilename, na.strings=c(&quot;NA&quot;,&quot;#DIV/0!&quot;, &quot;&quot;))  
}

testingDataURL&lt;-&quot;https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv&quot;
testFilename&lt;-&quot;testData.csv&quot;
if (file.exists(testFilename)) {
        testingData&lt;-read.csv(testFilename, na.strings=c(&quot;NA&quot;,&quot;#DIV/0!&quot;, &quot;&quot;))    
} else {
        download.file(testingDataURL, destfile = testFilename, method = &quot;curl&quot;)
        testingData&lt;-read.csv(testFilename, na.strings=c(&quot;NA&quot;,&quot;#DIV/0!&quot;, &quot;&quot;))
}
</code></pre>

<p><strong>2. Preparing the data:</strong></p>

<p>First of all, I clean the data removing columns only containing missing values (NAs) and unnecessary variables related to data acquisition 
(i.e., [X, user_name, raw_timestamp_part_1, raw_timestamp_part_2, cvtd_timestamp, new_window, num_window]).
Variables with low variance (Near Zero Variance), were also removed.</p>

<pre><code class="r">#Delete columns with all missing values
trainingData&lt;-trainingData[,colSums(is.na(trainingData)) == 0]
testingData &lt;-testingData[,colSums(is.na(testingData)) == 0]

#Discard unnecessary variables
trainingData   &lt;-trainingData[,-c(1:7)]
testingData &lt;-testingData[,-c(1:7)]

#Removing near zero covariatees
nearzerovarTr &lt;- nearZeroVar(trainingData, saveMetrics = TRUE)
trainingData &lt;- trainingData[, !nearzerovarTr$nzv]

nearzerovarTe &lt;- nearZeroVar(trainingData, saveMetrics = TRUE)
testingData &lt;- testingData[, !nearzerovarTe$nzv]

dim(trainingData)
</code></pre>

<pre><code>## [1] 19622    53
</code></pre>

<pre><code class="r">dim(testingData)
</code></pre>

<pre><code>## [1] 20 53
</code></pre>

<p>After cleaning the data, <strong>53</strong> variables were selected to define the model, i.e., <strong>roll_belt, pitch_belt, yaw_belt, total_accel_belt, gyros_belt_x, gyros_belt_y, gyros_belt_z, accel_belt_x, accel_belt_y, accel_belt_z, magnet_belt_x, magnet_belt_y, magnet_belt_z, roll_arm, pitch_arm, yaw_arm, total_accel_arm, gyros_arm_x, gyros_arm_y, gyros_arm_z, accel_arm_x, accel_arm_y, accel_arm_z, magnet_arm_x, magnet_arm_y, magnet_arm_z, roll_dumbbell, pitch_dumbbell, yaw_dumbbell, total_accel_dumbbell, gyros_dumbbell_x, gyros_dumbbell_y, gyros_dumbbell_z, accel_dumbbell_x, accel_dumbbell_y, accel_dumbbell_z, magnet_dumbbell_x, magnet_dumbbell_y, magnet_dumbbell_z, roll_forearm, pitch_forearm, yaw_forearm, total_accel_forearm, gyros_forearm_x, gyros_forearm_y, gyros_forearm_z, accel_forearm_x, accel_forearm_y, accel_forearm_z, magnet_forearm_x, magnet_forearm_y, magnet_forearm_z, classe</strong>.</p>

<p>Next, I partition the training data set into two subdata sets (i.e., 70% for inTraining, 30% for inTesting) to perform cross-validation. </p>

<pre><code class="r">#Data splitting into two subdata sets

inTrain &lt;- createDataPartition(y=trainingData$classe, p=0.7, list=FALSE)
subTraining &lt;- trainingData[inTrain, ]
subTesting &lt;- trainingData[-inTrain, ]
dim(subTraining)
</code></pre>

<pre><code>## [1] 13737    53
</code></pre>

<pre><code class="r">dim(subTesting)
</code></pre>

<pre><code>## [1] 5885   53
</code></pre>

<p><strong>3. Using different classification algorithms to generate the prediction model:</strong></p>

<p>I next examined the fit of three different models (Decision Tree, Bagging and Random Forest) to the subTraining data set, and then I tested them on the subTesting data. The best fitting model will be finally used on the test data.</p>

<p><em>3.1 Using a decision tree as first prediction model:</em></p>

<pre><code class="r">#Fitting the model
modDT &lt;- rpart(classe ~ ., method = &quot;class&quot;, data = subTraining)

#Plotting of the decision tree
rpart.plot(modDT, main=&quot;Classification Tree&quot;, cex = 1.5, under = TRUE) #faclen=0
</code></pre>

<p><img src="figure/unnamed-chunk-41.png" alt="plot of chunk unnamed-chunk-4"/> </p>

<pre><code class="r">#Fancy plotting of the decision tree
fancyRpartPlot(modDT, main=&quot;Classification Tree&quot;, cex = 1.15, under = TRUE)
</code></pre>

<p><img src="figure/unnamed-chunk-42.png" alt="plot of chunk unnamed-chunk-4"/> </p>

<pre><code class="r">#Predicting on the testing subdata set
predictionDT &lt;- predict(modDT, subTesting, type = &quot;class&quot;)
cMDT &lt;- confusionMatrix(predictionDT,subTesting$classe)
cMDT
</code></pre>

<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    A    B    C    D    E
##          A 1500  259   20  108   48
##          B   32  626   85   43   80
##          C   43  117  825  122  137
##          D   55   86   63  630   56
##          E   44   51   33   61  761
## 
## Overall Statistics
##                                         
##                Accuracy : 0.738         
##                  95% CI : (0.726, 0.749)
##     No Information Rate : 0.284         
##     P-Value [Acc &gt; NIR] : &lt;2e-16        
##                                         
##                   Kappa : 0.667         
##  Mcnemar&#39;s Test P-Value : &lt;2e-16        
## 
## Statistics by Class:
## 
##                      Class: A Class: B Class: C Class: D Class: E
## Sensitivity             0.896    0.550    0.804    0.654    0.703
## Specificity             0.897    0.949    0.914    0.947    0.961
## Pos Pred Value          0.775    0.723    0.663    0.708    0.801
## Neg Pred Value          0.956    0.898    0.957    0.933    0.935
## Prevalence              0.284    0.194    0.174    0.164    0.184
## Detection Rate          0.255    0.106    0.140    0.107    0.129
## Detection Prevalence    0.329    0.147    0.211    0.151    0.161
## Balanced Accuracy       0.896    0.750    0.859    0.800    0.832
</code></pre>

<p><em>3.2 Using Bagging as second prediction model:</em></p>

<pre><code class="r">#Fitting the model
modBA &lt;- bagging(classe ~ ., method = &quot;class&quot;, data = subTraining)

#Predicting on the testing subdata set and printing the resulting confusion matrix and statistics
predictionBA &lt;- predict(modBA, subTesting, type = &quot;class&quot;)
cMBA &lt;- confusionMatrix(predictionBA,subTesting$classe)
cMBA
</code></pre>

<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    A    B    C    D    E
##          A 1669    9    1    2    0
##          B    2 1119    6    2    2
##          C    2    9 1008    7    2
##          D    1    2    8  953    2
##          E    0    0    3    0 1076
## 
## Overall Statistics
##                                         
##                Accuracy : 0.99          
##                  95% CI : (0.987, 0.992)
##     No Information Rate : 0.284         
##     P-Value [Acc &gt; NIR] : &lt;2e-16        
##                                         
##                   Kappa : 0.987         
##  Mcnemar&#39;s Test P-Value : NA            
## 
## Statistics by Class:
## 
##                      Class: A Class: B Class: C Class: D Class: E
## Sensitivity             0.997    0.982    0.982    0.989    0.994
## Specificity             0.997    0.997    0.996    0.997    0.999
## Pos Pred Value          0.993    0.989    0.981    0.987    0.997
## Neg Pred Value          0.999    0.996    0.996    0.998    0.999
## Prevalence              0.284    0.194    0.174    0.164    0.184
## Detection Rate          0.284    0.190    0.171    0.162    0.183
## Detection Prevalence    0.286    0.192    0.175    0.164    0.183
## Balanced Accuracy       0.997    0.990    0.989    0.993    0.997
</code></pre>

<p><em>3.3 Using random forest (improved bagging) as third prediction model:</em></p>

<pre><code class="r">#Fitting the model
modRF &lt;- randomForest(classe ~ ., method = &quot;class&quot;, data = subTraining)
#Predicting on the testing subdata set and printing the resulting confusion matrix and statistics
predictionRF &lt;- predict(modRF, subTesting, type = &quot;class&quot;)
cMRF &lt;- confusionMatrix(predictionRF,subTesting$classe)
cMRF
</code></pre>

<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    A    B    C    D    E
##          A 1672    3    0    0    0
##          B    2 1133    4    0    0
##          C    0    3 1022    7    0
##          D    0    0    0  957    4
##          E    0    0    0    0 1078
## 
## Overall Statistics
##                                         
##                Accuracy : 0.996         
##                  95% CI : (0.994, 0.998)
##     No Information Rate : 0.284         
##     P-Value [Acc &gt; NIR] : &lt;2e-16        
##                                         
##                   Kappa : 0.995         
##  Mcnemar&#39;s Test P-Value : NA            
## 
## Statistics by Class:
## 
##                      Class: A Class: B Class: C Class: D Class: E
## Sensitivity             0.999    0.995    0.996    0.993    0.996
## Specificity             0.999    0.999    0.998    0.999    1.000
## Pos Pred Value          0.998    0.995    0.990    0.996    1.000
## Neg Pred Value          1.000    0.999    0.999    0.999    0.999
## Prevalence              0.284    0.194    0.174    0.164    0.184
## Detection Rate          0.284    0.193    0.174    0.163    0.183
## Detection Prevalence    0.285    0.194    0.175    0.163    0.183
## Balanced Accuracy       0.999    0.997    0.997    0.996    0.998
</code></pre>

<p><strong>4. Comparing the different models and selecting the best fitting one:</strong></p>

<pre><code class="r">dfAccuracies &lt;- data.frame(cMDT$overall, cMBA$overall, cMRF$overall)
dfAccuracies
</code></pre>

<pre><code>##                cMDT.overall cMBA.overall cMRF.overall
## Accuracy          7.378e-01       0.9898       0.9961
## Kappa             6.667e-01       0.9871       0.9951
## AccuracyLower     7.264e-01       0.9869       0.9941
## AccuracyUpper     7.490e-01       0.9922       0.9975
## AccuracyNull      2.845e-01       0.2845       0.2845
## AccuracyPValue    0.000e+00       0.0000       0.0000
## McnemarPValue     6.165e-61          NaN          NaN
</code></pre>

<p>BY comparing the accuracies of the different models, I select random forest as the one displaying the highest one (Accuracy: <strong>0.9961</strong>), with a 95% confidence interval: <strong>0.9941 - 0.9975</strong>. As the estimated out-of-sample error rate of the Random Forest trained model (1-Accuracy) is less than 1%, we expect very few errors in predictions. Finally, I display the best fitting final model:</p>

<pre><code class="r">#List the variables by relative importance
varImp(modRF)
</code></pre>

<pre><code>##                      Overall
## roll_belt             917.51
## pitch_belt            489.33
## yaw_belt              615.09
## total_accel_belt      152.84
## gyros_belt_x           64.65
## gyros_belt_y           80.84
## gyros_belt_z          207.31
## accel_belt_x           86.38
## accel_belt_y           92.36
## accel_belt_z          262.30
## magnet_belt_x         165.92
## magnet_belt_y         277.19
## magnet_belt_z         273.38
## roll_arm              220.32
## pitch_arm             125.13
## yaw_arm               168.32
## total_accel_arm        73.75
## gyros_arm_x            91.09
## gyros_arm_y            95.01
## gyros_arm_z            43.30
## accel_arm_x           176.14
## accel_arm_y           108.95
## accel_arm_z            99.73
## magnet_arm_x          178.83
## magnet_arm_y          161.87
## magnet_arm_z          130.89
## roll_dumbbell         293.93
## pitch_dumbbell        128.14
## yaw_dumbbell          169.66
## total_accel_dumbbell  198.30
## gyros_dumbbell_x       88.41
## gyros_dumbbell_y      169.37
## gyros_dumbbell_z       61.14
## accel_dumbbell_x      185.18
## accel_dumbbell_y      282.39
## accel_dumbbell_z      232.99
## magnet_dumbbell_x     353.89
## magnet_dumbbell_y     450.69
## magnet_dumbbell_z     522.37
## roll_forearm          424.23
## pitch_forearm         543.78
## yaw_forearm           123.75
## total_accel_forearm    74.35
## gyros_forearm_x        54.38
## gyros_forearm_y        92.13
## gyros_forearm_z        61.81
## accel_forearm_x       227.85
## accel_forearm_y        97.21
## accel_forearm_z       163.88
## magnet_forearm_x      154.65
## magnet_forearm_y      154.66
## magnet_forearm_z      191.95
</code></pre>

<p><strong>5. Apply the best fitting model to the test data:</strong></p>

<p>I then applied the machine Random Forest learning algorithm I built to each of the 20 test cases in the testing data set.</p>

<pre><code class="r"># Predict testing results using trained best fitting model
results &lt;- predict(modRF, testingData, type=&quot;class&quot;)
results
</code></pre>

<pre><code>##  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 
##  B  A  B  A  A  E  D  B  A  A  B  C  B  A  E  E  A  B  B  B 
## Levels: A B C D E
</code></pre>

<pre><code class="r">#Save the best fitting model model into a file for subsequent usage
save(modRF, file=&quot;modRF.R&quot;)

resultsfolder &lt;- &quot;/Volumes/Data/E-courses/Johns\ Hopkins\ University\ Data\ Science/Practical_Machine_Learning/Project/Answers&quot;
setwd(resultsfolder)

pml_write_files = function(x){
  n = length(x)
  for(i in 1:n){
    filename = paste0(&quot;problem_id_&quot;,i,&quot;.txt&quot;)
    write.table(x[i],file=filename,quote=FALSE,row.names=FALSE,col.names=FALSE)
  }
}

pml_write_files(results)
</code></pre>

